name: expense_tracker
description: A Flutter expense tracker application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Localization
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.7
  
  # HTTP & API
  dio: ^5.3.2
  
  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # UI & Charts
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  
  # Date & Time
  intl: ^0.18.1
  
  # Routing
  go_router: ^12.1.1
  
  # Forms & Validation
  form_builder_validators: ^9.1.0
  
  # Icons
  cupertino_icons: ^1.0.2
  
  # Notifications
  flutter_local_notifications: ^16.3.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  timezone: ^0.9.2
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
