"""Add enhanced user security fields

Revision ID: 002_enhanced_user_security
Revises: 001_initial_migration
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '002_enhanced_user_security'
down_revision = '001_initial_migration'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns to users table
    op.add_column('users', sa.Column('full_name', sa.String(100), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(20), nullable=False, default='user'))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, default=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, default=False))
    op.add_column('users', sa.Column('phone', sa.String(20), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(255), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, default=0))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()))
    
    # Modify password_hash column to increase length for bcrypt
    op.alter_column('users', 'password_hash',
                    existing_type=sa.String(100),
                    type_=sa.String(255),
                    nullable=False)
    
    # Add new columns to categories table
    op.add_column('categories', sa.Column('icon', sa.String(10), nullable=True))
    op.add_column('categories', sa.Column('color', sa.String(7), nullable=True))
    op.add_column('categories', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()))
    
    # Add foreign key constraint for categories.user_id
    op.create_foreign_key('fk_categories_user_id', 'categories', 'users', ['user_id'], ['id'])
    
    # Create indexes for performance
    op.create_index('idx_users_role', 'users', ['role'])
    op.create_index('idx_users_active', 'users', ['is_active'])
    op.create_index('idx_users_verified', 'users', ['is_verified'])
    op.create_index('idx_users_locked', 'users', ['locked_until'])
    op.create_index('idx_categories_user_id', 'categories', ['user_id'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('idx_categories_user_id', 'categories')
    op.drop_index('idx_users_locked', 'users')
    op.drop_index('idx_users_verified', 'users')
    op.drop_index('idx_users_active', 'users')
    op.drop_index('idx_users_role', 'users')
    
    # Drop foreign key constraint
    op.drop_constraint('fk_categories_user_id', 'categories', type_='foreignkey')
    
    # Remove columns from categories table
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'user_id')
    op.drop_column('categories', 'color')
    op.drop_column('categories', 'icon')
    
    # Revert password_hash column length
    op.alter_column('users', 'password_hash',
                    existing_type=sa.String(255),
                    type_=sa.String(100),
                    nullable=False)
    
    # Remove columns from users table
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_column('users', 'full_name')
    
    # ### end Alembic commands ###
